name: Build

on:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read 
  packages: read

jobs:
  build-base-gawc:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - name: Build Base Container
        shell: bash
        run: docker build -t ghcr.io/nano-dna-studios/gawc-base:latest ./BaseContainer

  build-variant-gawcs:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: build-base-gawc
    strategy:
      matrix:
        variants: ["dotnet", "node"]
    steps:
      - name: Build Variant Container
        shell: bash
        run: docker build -t ghcr.io/nano-dna-studios/gawc-${{ matrix.variants }}:latest ./Variants/${{ matrix.variants }}