name: Build

on:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read 
  packages: read

jobs:
  setup:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build-base-gawc:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: setup
    steps:
      - name: Build Base Container
        shell: bash
        run: docker build -t ghcr.io/nano-dna-studios/gawc-base:latest ./BaseContainer

  find-variants:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: build-base-gawc
    outputs:
      variants: ${{ steps.set-variants.outputs.variants }}
    steps:
      - name: Set Variants
        id: set-variants
        shell: bash
        run: |
          variants=()
          for folder in ./Variants/*; do
            if [ -d "$folder" ]; then
              variant=$(basename "$folder")
              variants+=("\"$variant\"")
            fi
          done

          echo "Found variants: ${variants[*]}"

  build-variant-gawcs:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: build-base-gawc
    strategy:
      matrix:
        variants: ["dotnet", "node"]
    steps:
      - name: Build Variant Container
        shell: bash
        run: docker build -t ghcr.io/nano-dna-studios/gawc-${{ matrix.variants }}:latest ./Variants/${{ matrix.variants }}